/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package metodista;

/**
 *
 * @author 248543
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtExibir = new javax.swing.JLabel();
        vntMaiorValor = new javax.swing.JButton();
        btnMenorValor = new javax.swing.JButton();
        bntListaInvertida = new javax.swing.JButton();
        bntMediaDosValores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Vetores:");

        txtExibir.setText("0");

        vntMaiorValor.setText("Maior Valor");
        vntMaiorValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vntMaiorValorActionPerformed(evt);
            }
        });

        btnMenorValor.setText("Menor Valor");
        btnMenorValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenorValorActionPerformed(evt);
            }
        });

        bntListaInvertida.setText("Lista Invertida");
        bntListaInvertida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntListaInvertidaActionPerformed(evt);
            }
        });

        bntMediaDosValores.setText("Media dos Valores");
        bntMediaDosValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMediaDosValoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtExibir, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(vntMaiorValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntListaInvertida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMenorValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntMediaDosValores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtExibir, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vntMaiorValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntListaInvertida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenorValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntMediaDosValores)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vntMaiorValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vntMaiorValorActionPerformed
    CaixaDeNumeros cdn = new CaixaDeNumeros();
    cdn.vetor();
    int resultado = cdn.maiorVetor();
    txtExibir.setText(String.valueOf(resultado));
    }//GEN-LAST:event_vntMaiorValorActionPerformed

    private void bntListaInvertidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntListaInvertidaActionPerformed
    CaixaDeNumeros cdn = new CaixaDeNumeros();
    cdn.vetor();
    int [] lista = cdn.listaInvertida();
    String resultado = "";
    for(int x= 0; x< lista.length; x++) {
        resultado+= String.valueOf(lista[x]) + ", ";
    }
    txtExibir.setText(resultado);
    }//GEN-LAST:event_bntListaInvertidaActionPerformed

    private void btnMenorValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenorValorActionPerformed
    CaixaDeNumeros cdn = new CaixaDeNumeros();
    cdn.vetor();
    int resultado = cdn.menorVetor();
    txtExibir.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btnMenorValorActionPerformed

    private void bntMediaDosValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMediaDosValoresActionPerformed
    CaixaDeNumeros cdn = new CaixaDeNumeros();
    cdn.vetor();
    int resultado = cdn.mediaDosVetores();
    txtExibir.setText(String.valueOf(resultado));
    }//GEN-LAST:event_bntMediaDosValoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntListaInvertida;
    private javax.swing.JButton bntMediaDosValores;
    private javax.swing.JButton btnMenorValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtExibir;
    private javax.swing.JButton vntMaiorValor;
    // End of variables declaration//GEN-END:variables
}
